name: 4d_gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - plyfile=0.8.1
  - python=3.8
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - colmap
  - pip:
    - tqdm==4.66.1
    - torchmetrics==0.11.4
    - imagesize==1.4.1
    - kornia==0.6.12
    - omegaconf==2.3.0

    
